
enum
{
CALIBRATION_ACCEL_WAITING,
CALIBRATION_ACCEL_RECORDING,
CALIBRATION_ACCEL_COMPLETED,
CALIBRATION_GYRO_READY,
CALIBRATION_GYRO_RECORDING,
CALIBRATION_COMPLETED,
};

#define CALIBRATION_BLINK_DELAY_MASK 0x0F00
#define CALIBRATION_BLINK_DELAY_LONG 0x0300
#define CALIBRATION_BLINK_DELAY 0x0200
#define CALIBRATION_BLINK_DELAY_SHORT 0x0100

enum
{
AXIS_X_PLUS,
AXIS_X_MINUS,
AXIS_Y_PLUS,
AXIS_Y_MINUS,
AXIS_Z_PLUS,
AXIS_Z_MINUS,
AXIS_NONE
};

int calibrate();
